/**
 * Content Types - Core content type definitions for CXO Academy Platform
 * 
 * These types define the structure of all educational content
 * generated by the AI content engine.
 */

// ============================================
// Base Types
// ============================================

export type SkillLevel = 'beginner' | 'intermediate' | 'advanced' | 'expert';

export type TopicCategory = 
  | 'ai-ml-engineering'
  | 'web-development'
  | 'cloud-computing'
  | 'cybersecurity'
  | 'devops-sre';

export type ContentStatus = 
  | 'draft'
  | 'review'
  | 'published'
  | 'archived'
  | 'needs-update';

export type ProgrammingLanguage = 
  | 'python'
  | 'javascript'
  | 'typescript'
  | 'java'
  | 'go'
  | 'rust'
  | 'sql'
  | 'bash'
  | 'other';

// ============================================
// Course Types
// ============================================

export interface CourseMetadata {
  id: string;
  title: string;
  slug: string;
  description: string;
  category: TopicCategory;
  skillLevel: SkillLevel;
  tags: string[];
  prerequisites: string[];
  learningObjectives: string[];
  estimatedHours: number;
  author: string;
  createdAt: Date;
  updatedAt: Date;
  status: ContentStatus;
  version: string;
  seoMetadata: SEOMetadata;
}

export interface Course {
  metadata: CourseMetadata;
  modules: Module[];
  assessments: Assessment[];
  resources: Resource[];
}

export interface SEOMetadata {
  title: string;
  description: string;
  keywords: string[];
  ogImage?: string;
}

// ============================================
// Module & Lesson Types
// ============================================

export interface Module {
  id: string;
  courseId: string;
  order: number;
  title: string;
  description: string;
  lessons: Lesson[];
  duration: number; // in minutes
}

export interface Lesson {
  id: string;
  moduleId: string;
  order: number;
  title: string;
  slug: string;
  description: string;
  content: LessonContent;
  codeExamples: CodeExample[];
  exercises: Exercise[];
  resources: Resource[];
  duration: number; // in minutes
  skillLevel: SkillLevel;
  learningObjectives: string[];
  keyTakeaways: string[];
  createdAt: Date;
  updatedAt: Date;
  version: string;
}

export interface LessonContent {
  introduction: string;
  sections: ContentSection[];
  conclusion: string;
  summary: string;
}

export interface ContentSection {
  id: string;
  title: string;
  content: string;
  type: 'text' | 'code' | 'diagram' | 'interactive' | 'video';
  codeBlock?: CodeBlock;
}

export interface CodeBlock {
  language: ProgrammingLanguage;
  code: string;
  explanation: string;
  filename?: string;
  runnable?: boolean;
  expectedOutput?: string;
}

// ============================================
// Code Example Types
// ============================================

export interface CodeExample {
  id: string;
  lessonId: string;
  title: string;
  description: string;
  language: ProgrammingLanguage;
  code: string;
  explanation: string;
  complexity: 'basic' | 'intermediate' | 'advanced';
  tags: string[];
  prerequisites: string[];
  expectedOutput?: string;
  testCases?: TestCase[];
  createdAt: Date;
  updatedAt: Date;
}

export interface TestCase {
  id: string;
  input: string;
  expectedOutput: string;
  description: string;
}

// ============================================
// Assessment Types
// ============================================

export interface Assessment {
  id: string;
  courseId?: string;
  lessonId?: string;
  title: string;
  description: string;
  type: AssessmentType;
  difficulty: SkillLevel;
  questions: Question[];
  passingScore: number;
  timeLimit?: number; // in minutes
  attempts: number;
  createdAt: Date;
  updatedAt: Date;
}

export type AssessmentType = 
  | 'quiz'
  | 'exam'
  | 'coding-challenge'
  | 'project'
  | 'practice';

export interface Question {
  id: string;
  type: QuestionType;
  question: string;
  options?: QuestionOption[];
  correctAnswer: string | string[];
  explanation: string;
  points: number;
  difficulty: SkillLevel;
  codeSnippet?: string;
  language?: ProgrammingLanguage;
  tags: string[];
}

export type QuestionType = 
  | 'multiple-choice'
  | 'multiple-select'
  | 'true-false'
  | 'fill-blank'
  | 'code-completion'
  | 'short-answer'
  | 'code-analysis';

export interface QuestionOption {
  id: string;
  text: string;
  isCorrect: boolean;
}

// ============================================
// Exercise Types
// ============================================

export interface Exercise {
  id: string;
  lessonId: string;
  title: string;
  description: string;
  type: ExerciseType;
  difficulty: SkillLevel;
  instructions: string[];
  starterCode?: string;
  solution?: string;
  hints: string[];
  testCases: TestCase[];
  points: number;
}

export type ExerciseType = 
  | 'coding'
  | 'conceptual'
  | 'debugging'
  | 'optimization'
  | 'design';

// ============================================
// Resource Types
// ============================================

export interface Resource {
  id: string;
  title: string;
  description: string;
  type: ResourceType;
  url?: string;
  content?: string;
  author?: string;
  publishedAt?: Date;
  tags: string[];
}

export type ResourceType = 
  | 'article'
  | 'video'
  | 'documentation'
  | 'book'
  | 'tool'
  | 'repository'
  | 'paper'
  | 'cheatsheet';

// ============================================
// Research Types
// ============================================

export interface ResearchTopic {
  id: string;
  topic: string;
  category: TopicCategory;
  keywords: string[];
  sources: ResearchSource[];
  summary: string;
  keyFindings: string[];
  relevanceScore: number;
  lastResearched: Date;
  needsUpdate: boolean;
}

export interface ResearchSource {
  id: string;
  title: string;
  url: string;
  author?: string;
  publishedAt?: Date;
  summary: string;
  credibility: 'high' | 'medium' | 'low';
  type: 'paper' | 'article' | 'documentation' | 'release' | 'news';
}

// ============================================
// User & Progress Types
// ============================================

export interface UserProgress {
  userId: string;
  courseId: string;
  completedLessons: string[];
  assessmentScores: Map<string, number>;
  currentModule: string;
  currentLesson: string;
  timeSpent: number; // in minutes
  lastAccessed: Date;
  skillLevel: SkillLevel;
  notes: UserNote[];
}

export interface UserNote {
  id: string;
  lessonId: string;
  content: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ContentRecommendation {
  courseId: string;
  lessonId?: string;
  reason: string;
  relevanceScore: number;
  type: 'next' | 'related' | 'prerequisite' | 'review';
}

// ============================================
// Content Generation Types
// ============================================

export interface GenerationRequest {
  type: 'course' | 'lesson' | 'quiz' | 'code-example' | 'update';
  topic: string;
  category: TopicCategory;
  skillLevel: SkillLevel;
  context?: string;
  existingContent?: string;
  requirements?: string[];
}

export interface GenerationResult<T> {
  success: boolean;
  content?: T;
  error?: string;
  tokensUsed: number;
  cached: boolean;
  generatedAt: Date;
}

export interface ContentUpdate {
  id: string;
  contentId: string;
  contentType: 'course' | 'lesson' | 'code-example';
  reason: string;
  changes: ContentChange[];
  appliedAt: Date;
}

export interface ContentChange {
  field: string;
  oldValue: string;
  newValue: string;
  reason: string;
}

// ============================================
// Cache Types
// ============================================

export interface CacheEntry<T> {
  key: string;
  content: T;
  createdAt: Date;
  expiresAt: Date;
  hitCount: number;
  tags: string[];
}

export interface CacheStats {
  totalEntries: number;
  totalHits: number;
  totalMisses: number;
  hitRate: number;
  oldestEntry: Date;
  newestEntry: Date;
}

// ============================================
// Weekly Schedule Types
// ============================================

export interface WeeklySchedule {
  week: number;
  year: number;
  monday: DayTask;
  tuesday: DayTask;
  wednesday: DayTask;
  thursday: DayTask;
  friday: DayTask;
}

export interface DayTask {
  date: Date;
  task: ScheduledTask;
  status: 'pending' | 'in-progress' | 'completed' | 'failed';
  results?: GenerationResult<unknown>;
}

export interface ScheduledTask {
  type: 'research' | 'lesson-generation' | 'code-examples' | 'quizzes' | 'updates';
  topics: string[];
  category: TopicCategory;
  priority: 'high' | 'medium' | 'low';
}

// ============================================
// Additional Research Types (for AI agents)
// ============================================

export type ResearchSourceType = 'paper' | 'article' | 'documentation' | 'release' | 'news';

export interface ResearchRequest {
  topic: string;
  depth?: 'brief' | 'detailed' | 'comprehensive';
  sources?: string[];
  timeframe?: string;
}

export interface Trend {
  id: string;
  name: string;
  description: string;
  category: string;
  momentum: 'rising' | 'stable' | 'declining';
  relevance: number;
  sources: ResearchedSource[];
}

export interface ResearchedSource {
  id: string;
  title: string;
  url: string;
  author?: string;
  publishedAt?: Date;
  summary: string;
  type: ResearchSourceType;
  credibility: 'high' | 'medium' | 'low';
}

export interface ResearchResult {
  id: string;
  topic: string;
  summary: string;
  keyInsights: string[];
  sources: ResearchedSource[];
  trends: Trend[];
  recommendations: string[];
  generatedAt: Date;
  expiresAt: Date;
}
